# Generated by Django 5.2.4 on 2025-08-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='outlet_images/')),
                ('is_trending', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
